### PR TITLE
Multi context refactor

### PR DESCRIPTION
**Pull request by Revolyssup**
Signed-off-by: ashish <ashishjaitiwari15112000@gmail.com>

**Description**

This PR fixes #

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
A few red ❌s to investigate

**Comment by Revolyssup** [comment]
> A few red xs to investigate

This is a breaking change so the failed checks wont succeed

**Comment by Revolyssup** [comment]
> A few red xs to investigate

I will signal when this will be ready for merge along with all other adapters.

**Comment by leecalcote** [comment]
> > A few red xs to investigate
> 
> This is a breaking change so the failed checks wont succeed

Oh, I see. Ok, got it.

**Pull request merged**
