### PR TITLE
[Lifecycle] install latest OSM and some refactoring

### LINKED ISSUE #101: [Lifecycle] remove version hardcoding
**Enhancement Description**
Support multiple versions in the OSM adapter.

**Related Challenges**
* Currently the OSM adapter only installs OSM v0.6.0. We need to be able to fetch binaries for the latest releases and use the latest OSM.
* Also, when reading binaries from `~/.meshery/bin` it expects them to be in the form `osm-v0.6.0`. This is a side effect of point one but should be kept in mind.

---
**Alternatives**
Using `docker cp $binPath meshery_meshery-osm_1:/root/.meshery/bin/osm-v0.6.0` for tricking the adapater to believe that the current binary is for osm-v0.6.0. Too hacky.

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See Meshery site designs in this [Figma designfile](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1). Fill-in the [Layer5 Community Member Form](https://layer5.io/newcomer) and join the [Layer5 Community Slack](http://slack.layer5.io) for access.

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>

**Description**

This PR fixes #101 

**Notes for Reviewers**
* No hard coded versions
* Install using helm charts
* Sidecar injection without using OSM cli (label and annotate namespace)
* Some cleanup and refactoring

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
That's a fine looking set of enhancements.

**Comment by leecalcote** [comment]
It's so nice to see the cli ripped out of here. 

I wasn't able to check versions.go, and, am curious as to how "latest" and specific versions is working.

**Review by leecalcote — APPROVED** [review]

**Comment by DelusionalOptimist** [comment]
hmm... seems like some files got ignored somehow while staging changes :thinking:

**Comment by DelusionalOptimist** [comment]
Yeah :man_facepalming: 
https://github.com/meshery/meshery-osm/blob/master/.gitignore#L20

**Comment by DelusionalOptimist** [comment]
> I wasn't able to check versions.go, and, am curious as to how "latest" and specific versions is working.

Right now, it fetches the latest release tag, fetches corresponding helm chart from https://openservicemesh.github.io/osm/ and installs.

For users specified versions, temporarily, we can read user supplied helm charts and install the version specified in that, overriding the fetched release tag ( this is yet to be added )

A nastier approach to specific versioning might be modifying meshops handlers or request structs but I believe it would be better handled once by pattern based approach for adapter operations.

**Comment by leecalcote** [comment]
> Right now, it fetches the latest release tag, fetches corresponding helm chart from https://openservicemesh.github.io/osm/ and installs.

That's great.

> For users' specified versions, temporarily, we can read user supplied helm charts and install the version specified in that, overriding the fetched release tag ( this is yet to be added )

This will work well with one change: allow users to specify version number, not require them to supply helm charts. Present the user with a version number in a dropdown in the UI. 

Multiple versions should be registered in the capabilities database and presented to the user in the Meshery UI, based on the versions supported by patterns. We should also have a perpetual "Latest" entry in that dropdown. 

// @Revolyssup @Shreyas220 @sayantan1413 @sudo-NithishKarthik @utkarsh-pro, @bariqhibat, if this is already supported in pattern registration, we just need to expose in the UI. Either way, will one of you open one or two issues on this depending on if only UI updates are needed or if MeshKit / Meshery Adapter Library changes are needed?

> A nastier approach to specific versioning might be modifying meshops handlers or request structs but I believe it would be better handled by pattern based approach for adapter operations.

**Pull request merged**
