### PR TITLE
Upgrading TestOSM to v2 of centralised e2e tests

### PR DESCRIPTION
**Pull request by yash37158**
**Description**

This PR fixes # 239
Migration to v2 for all the adapters, therefore it was necessary to migrate the OSM adapter to v2 for all E2E tests.

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by yash37158** [comment]
Hey @Revolyssup, as discussed in the meeting I have did the changes

**Comment by leecalcote** [comment]
Thanks, @yash37158 👍

**Comment by leecalcote** [comment]
New build checks running...

**Comment by yash37158** [comment]
Your welcome @leecalcote

**Comment by Revolyssup** [comment]
> Your welcome @leecalcote

Thanks for this. Please make sure that this v2 version is used across all adapters.

**Review by Revolyssup — APPROVED** [review]

**Comment by yash37158** [comment]
Yeah Sure @Revolyssup

**Comment by yash37158** [comment]
can you please merge the PR

**Comment by leecalcote** [comment]
Thanks, @yash37158 👍

**Pull request merged**
