### PR TITLE
move to thread-safe viper

### LINKED ISSUE #106: Adapter Operations are thread unsafe
Description
OSM Adapter operations are thread unsafe at the moment due its usage of meshery-adapter-library viper config provider.

Expected Behavior
Operations should be thread safe. This is achievable by replacing meshery-adapter-library config provider implementation with meshkit config provider implementation which share similar interfaces.

Contributor Resources
Refer Istio Adapter to see how config provider can be replaced

### PR DESCRIPTION
**Pull request by sayantan1413**
Signed-off-by: sayantan1413 <sayantanbose2001@gmail.com>

**Description**

Operations are now thread safe. This has been done by replacing meshery-adapter-library config provider implementation with meshkit config provider implementation which share similar interfaces.

This PR fixes #106 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by utkarsh-pro — APPROVED** [review]
LGTM. Thank you much for taking this initiative @sayantan1413.

**Comment by utkarsh-pro** [comment]
@DelusionalOptimist we are facing similar workflow failure in multiple PRs now. Can you look into it?

**Comment by utkarsh-pro** [comment]
@sayantan1413 I think you maybe interested in adding similar support to other adapters like `traefik-mesh`, `nginx-mesh`.

**Comment by DelusionalOptimist** [comment]
> @DelusionalOptimist we are facing similar workflow failure in multiple PRs now. Can you look into it?

@utkarsh-pro some trouble with the module's hosting. Has been fixed from their end. Should work fine everywhere now. :+1:

**Pull request merged**
