### PR TITLE
Upgrade to Go 1.19

### PR DESCRIPTION
**Pull request by acald-creator**
Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>

**Description**

This PR is related to https://github.com/meshery/meshery/issues/6220

- Upgrade to Go 1.19
- Updated template content and paths, as OSM have moved to a newer version and newer location

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ x ] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Thank you.

Merge conflict...

**Comment by leecalcote** [comment]
Some high quality work here. 🥇

**Comment by acald-creator** [comment]
Sometimes I hate making changes via GitHub

**Comment by leecalcote** [comment]
go.sum reconciliation on the web interface would be a nightmare. 

@acald-creator, if you haven't tried this before, you might get a kick out of it: Press `.`.

**Comment by acald-creator** [comment]
took longer than i thought but i got it back open

**Comment by leecalcote** [comment]
@Revolyssup please review.

**Comment by leecalcote** [comment]
> @Revolyssup please review.

No review to offer, @Revolyssup?

**Comment by leecalcote** [comment]
> > @Revolyssup please review.
> 
> No review to offer, @Revolyssup?

Calling on @Revolyssup...

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
